# Generated by Django 6.0.6 on 2026-10-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlternativeSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("country_of_origin", models.CharField(max_length=100)),
                (
                    "product_categories",
                    models.JSONField(
                        default=list,
                        help_text="Names of the product categories supplied, e.g. ['Dried fruit'].",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        help_text="Typical days from order to delivery."
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternative_suppliers",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"),
                        name="unique_alt_supplier_name_per_company",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("country_of_origin", models.CharField(max_length=100)),
                (
                    "product_categories",
                    models.JSONField(
                        default=list,
                        help_text="Names of the product categories supplied, e.g. ['Dried fruit'].",
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        help_text="Typical days from order to delivery."
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_suppliers",
                        to="tenants.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"),
                        name="unique_user_supplier_name_per_company",
                    )
                ],
            },
        ),
    ]
