# Generated by Django 6.0.6 on 2026-10-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_missing_models_and_invitations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logisticprovider",
            name="phone_number",
            field=models.CharField(max_length=32),
        ),
    ]
