# Generated by Django 6.0.6 on 2026-10-05 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
        ("pricing", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplierinvoice",
            name="invoice_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="supplierinvoice",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="inventory.supplier",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierinvoice",
            constraint=models.UniqueConstraint(
                fields=("company", "invoice_number"),
                name="unique_invoice_number_per_company",
            ),
        ),
    ]
