# Generated by Django 6.0.6 on 2026-10-09 09:04

import pricing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0003_supplier_invoice_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierinvoice",
            name="file",
            field=models.FileField(
                blank=True,
                help_text="The scanned or PDF invoice (PDF, PNG or JPEG).",
                upload_to=pricing.models.invoice_upload_path,
            ),
        ),
    ]
