# Generated by Django 6.0.6 on 2026-10-03 19:16

import common.fields
from django.db import migrations


def encrypt_existing_tokens(apps, schema_editor):
    """Re-save every row: plaintext values are read as-is and written back encrypted."""
    ShopifyConnection = apps.get_model("sync", "ShopifyConnection")
    for connection in ShopifyConnection.objects.all():
        connection.save(update_fields=["access_token"])


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopifyconnection",
            name="access_token",
            field=common.fields.EncryptedTextField(),
        ),
        migrations.RunPython(encrypt_existing_tokens, migrations.RunPython.noop),
    ]
