# Generated by Django 6.0.6 on 2026-10-05 20:11

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0003_encrypt_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shopifyconnection",
            name="shop_domain",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[a-z0-9][a-z0-9-]*\\.myshopify\\.com$"),
                        "Enter a Shopify domain like 'my-store.myshopify.com'.",
                    )
                ],
            ),
        ),
    ]
