# Generated by Django 6.0.6 on 2026-10-02 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("inventory", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandalert",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_alerts",
                to="tenants.company",
            ),
        ),
        migrations.AddField(
            model_name="stockalert",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_alerts",
                to="inventory.product",
            ),
        ),
    ]
