# Generated by Django 6.0.6 on 2026-10-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_initial"),
        ("demand_calendar", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FreightRateCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_code",
                    models.CharField(
                        help_text="Shipping service or lane, e.g. 'CN-UK-SEA'.",
                        max_length=100,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GBP", max_length=3)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.AddField(
            model_name="demandalert",
            name="event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_up_alerts",
                to="demand_calendar.event",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("event__isnull", False)),
                fields=("company", "product", "event"),
                name="one_demand_alert_per_product_and_event",
            ),
        ),
        migrations.AddField(
            model_name="freightratecache",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="freight_rates",
                to="tenants.company",
            ),
        ),
        migrations.AddField(
            model_name="setting",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to="tenants.company",
            ),
        ),
        migrations.AddConstraint(
            model_name="freightratecache",
            constraint=models.UniqueConstraint(
                fields=("company", "service_code"), name="one_freight_rate_per_service"
            ),
        ),
        migrations.AddConstraint(
            model_name="setting",
            constraint=models.UniqueConstraint(
                fields=("company", "key"), name="one_setting_per_key"
            ),
        ),
    ]
