# Generated by Django 6.0.6 on 2026-10-09 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_missing_models_and_invitations"),
        ("demand", "0002_initial"),
        ("demand_calendar", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandalert",
            name="cultural_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_up_alerts",
                to="demand.culturalevent",
            ),
        ),
        migrations.AddConstraint(
            model_name="demandalert",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cultural_event__isnull", False)),
                fields=("company", "product", "cultural_event"),
                name="one_demand_alert_per_product_and_cultural_event",
            ),
        ),
    ]
