# Generated by Django 6.0.6 on 2026-10-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demand_calendar", "0001_initial"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="product_categories",
            field=models.ManyToManyField(to="inventory.productcategory"),
        ),
        migrations.AddField(
            model_name="demandalert",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demand_alerts",
                to="demand_calendar.event",
            ),
        ),
    ]
