# Generated by Django 6.0.6 on 2026-10-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="tenants.company",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="inventory.productcategory",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.product"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.stockbatch"
            ),
        ),
    ]
