# Generated by Django 6.0.6 on 2026-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockbatch",
            name="batch_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.UniqueConstraint(
                fields=("product", "batch_number"),
                name="unique_batch_number_per_product",
            ),
        ),
    ]
