# Generated by Django 6.0.6 on 2026-10-08 18:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_refresh_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="refreshtoken",
            name="rotated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="session_started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
