# Generated by Django 6.0.6 on 2026-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_refresh_token_session_limits"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinvitation",
            name="invited_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="userinvitation",
            constraint=models.UniqueConstraint(
                fields=("company", "invited_email"),
                name="one_invitation_per_email_per_company",
            ),
        ),
    ]
