"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import hashlib
import re
import warnings
from pathlib import Path
from decouple import config
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# The key (and anything derived from it: JWTs, signed tokens, the default field-encryption key) must
# not be guessable. This refuses the placeholder that was once committed to this public repository
# (only its hash is kept here) and anything too short, unless DEBUG is on.
_PUBLISHED_SECRET_KEY_HASHES = {'b7fc4838f5a36c8d1940b56fe2df734293434da17cca35a4e3f82d66ead6aa0d'}
_secret_key_problem = None
if hashlib.sha256(SECRET_KEY.encode()).hexdigest() in _PUBLISHED_SECRET_KEY_HASHES:
    _secret_key_problem = 'SECRET_KEY is the placeholder that was committed to the public repository'
elif len(SECRET_KEY) < 32:
    _secret_key_problem = 'SECRET_KEY is shorter than 32 characters'
if _secret_key_problem:
    _advice = (
        "Generate one with: python -c \"from django.core.management.utils import "
        "get_random_secret_key; print(get_random_secret_key())\""
    )
    if not DEBUG:
        raise ImproperlyConfigured(f'{_secret_key_problem}. {_advice}')
    warnings.warn(f'{_secret_key_problem}. {_advice}', stacklevel=1)

# Comma- or whitespace-separated, e.g. "localhost,127.0.0.1" or "localhost 127.0.0.1 [::1]".
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='127.0.0.1', cast=lambda v: [h for h in re.split(r'[,\s]+', v) if h])


# Custom user model (email login, linked to a Company)
AUTH_USER_MODEL = 'tenants.CustomUser'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",
    "drf_spectacular",
    "inventory",  # Added the 'inventory' app to INSTALLED_APPS
    "demand",  # Added the 'demand' app to INSTALLED_APPS
    "logistics",  # Added the 'logistics' app to INSTALLED_APPS
    "pricing",  # Added the 'pricing' app to INSTALLED_APPS
    "sync",  # Added the 'sync' app to INSTALLED_APPS
    "common.apps.CommonConfig",
    "rest_framework",  # Added REST Framework to INSTALLED_APPS
    "tenants",  # Added 'tenants' app to INSTALLED_APPS
    "authentication",
    "demand_calendar",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

ASGI_APPLICATION = 'config.asgi.application'  # Added ASGI application setting

# Django REST framework
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "authentication.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_THROTTLE_RATES": {
        "login": config("LOGIN_THROTTLE_RATE", default="10/min"),
        "refresh": config("REFRESH_THROTTLE_RATE", default="30/min"),
    },
    "DEFAULT_PAGINATION_CLASS": "common.pagination.StandardResultsSetPagination",
    "EXCEPTION_HANDLER": "common.exceptions.custom_exception_handler",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Business IQ API",
    "VERSION": "1.0.0",
}

# Token lifetimes for authentication.jwt_handler / refresh_tokens
JWT_ACCESS_TOKEN_TTL_SECONDS = config('JWT_ACCESS_TOKEN_TTL_SECONDS', default=3600, cast=int)
JWT_REFRESH_TOKEN_TTL_SECONDS = config('JWT_REFRESH_TOKEN_TTL_SECONDS', default=14 * 24 * 3600, cast=int)
# Hard cap on a login session however often it is refreshed.
JWT_REFRESH_SESSION_MAX_AGE_SECONDS = config('JWT_REFRESH_SESSION_MAX_AGE_SECONDS', default=90 * 24 * 3600, cast=int)
# A refresh token used again within this many seconds of being exchanged is treated as a concurrent request
# (e.g. two browser tabs) and answered with a fresh token, instead of as theft. 0 disables the allowance.
JWT_REFRESH_REUSE_LEEWAY_SECONDS = config('JWT_REFRESH_REUSE_LEEWAY_SECONDS', default=10, cast=int)

# External services. The Hijri calendar (AlAdhan) and UK Trade Tariff APIs are public and need no key.
HTTP_TIMEOUT_SECONDS = config('HTTP_TIMEOUT_SECONDS', default=10, cast=int)
ALADHAN_API_URL = config('ALADHAN_API_URL', default='https://api.aladhan.com/v1')
HMRC_API_URL = config('HMRC_API_URL', default='https://www.trade-tariff.service.gov.uk/api/v2')
# Shopify retires API versions after 12 months; keep this on a supported one (https://shopify.dev/docs/api/usage/versioning).
SHOPIFY_API_VERSION = config('SHOPIFY_API_VERSION', default='2026-10')
DEFAULT_CUSTOMS_DUTY_RATE = config('DEFAULT_CUSTOMS_DUTY_RATE', default=0.0, cast=float)
FREIGHT_RATES_API_URL = config('FREIGHT_RATES_API_URL', default='')
RATE_CHANGE_THRESHOLD = config('RATE_CHANGE_THRESHOLD', default=5.0, cast=float)  # percent

# Encryption key(s) for EncryptedTextField, comma separated Fernet keys (first one encrypts).
# Generate with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
# Defaults to a key derived from SECRET_KEY.
FIELD_ENCRYPTION_KEYS = config('FIELD_ENCRYPTION_KEYS', default='', cast=lambda v: [k.strip() for k in v.split(',') if k.strip()])

# Cache (tariff and calendar lookups). Local memory by default; Redis when USE_REDIS_CACHE is set.
if config('USE_REDIS_CACHE', default=False, cast=bool):
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": f"redis://{config('REDIS_HOST', default='127.0.0.1')}:{config('REDIS_PORT', default=6379, cast=int)}/1",
        }
    }

# Redis
REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)

# Celery configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')

# Channel layer configuration
if config('USE_REDIS_CHANNELS', default=False, cast=bool):
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {"hosts": [(REDIS_HOST, REDIS_PORT)]},
        },
    }
else:
    CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')
if 'sqlite3' in DB_ENGINE:
    # DB_NAME is a file path, relative to the project root.
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": BASE_DIR / config('DB_NAME', default='db.sqlite3'),
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": config('DB_NAME', default='iq_db'),
            "USER": config('DB_USER', default='iq_user'),
            "PASSWORD": config('DB_PASSWORD', default=''),
            "HOST": config('DB_HOST', default='localhost'),
            "PORT": config('DB_PORT', default='5432'),
            "CONN_MAX_AGE": config('DB_CONN_MAX_AGE', default=60, cast=int),
        }
    }

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'