# .github/workflows/deploy.yml

name: Deploy Django Project with Docker and Push to AWS ECR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_DB: django_project
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - "5432:5432"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Build Docker image
      run: |
        docker build . --file Dockerfile.dev -t django_project:$GITHUB_SHA

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-url: ${{ secrets.AWS_ECR_REGISTRY_URL }}

    - name: Push Docker image to AWS ECR
      run: |
        docker tag django_project:$GITHUB_SHA ${{ secrets.AWS_ECR_REPOSITORY_URL }}
        docker push ${{ secrets.AWS_ECR_REPOSITORY_URL }}

    - name: Deploy to production server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.PRODUCTION_SERVER_HOST }}
        username: ${{ secrets.PRODUCTION_SERVER_USERNAME }}
        key: ${{ secrets.PRODUCTION_SERVER_KEY }}
        source: "django_project/*"
        target: "/var/www/html/django_project"

    - name: Restart Gunicorn service
      run: |
        ssh -i /home/runner/.ssh/id_rsa ${{ secrets.PRODUCTION_SERVER_USERNAME }}@${{ secrets.PRODUCTION_SERVER_HOST }} 'sudo systemctl restart gunicorn.service'